%: %.go
	go build -o $@ $<

step0_repl/step0_repl: step0_repl/step0_repl.go
step1_read_print/step1_read_print: step1_read_print/step1_read_print.go common/printer.go common/reader.go common/types.go
step2_eval/step2_eval: step2_eval/step2_eval.go common/printer.go common/reader.go common/types.go
